### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by JopStro** [Capati/wgpu-odin#2]
I mentioned in the PR I made that I found a number of issues with the wrapper in it's current state. I figured it would be helpful to make them known instead of working on them in private.
## ~~Custom allocators~~
~~I see you've tried you're best to utilise the custom allocator functionallity of odin, but most of it is, to put it bluntly, incorrect. The allocator argument should ideally only be used for allocating things that you are transfering ownership of to the user of the procedure, additionally the temp allocator should ideally be used for stuff limited to the scope of the function to save needing to keep track of too many individual lifetimes (`runtime.DEFAULT_TEMP_ALLOCATOR_TEMP_GUARD` is useful for this). I will probably focus on this first, but I reccomend exploring the odin core library source code for a better idea on how to utilise the custom allocator features correctly in the future as it uses the functionality quite extensively (I only found out about the guard functionality through looking at the core library source code myself).~~ addressed in PR #3

## ~~Dangling pointers in the SDL util procedure~~
~~The way the current way that the sdl util works leaves dangling pointers. This is because pointers given by pointer literals are only valid for the scope they are created in. The reason it currently works in the examples is because you've been lucky enough to not need to allocate enough stack memory to ovewrite them, you can test this my calling a reasonablely expensive function in between the descriptor constructor and the create_surface function (it should cause a segfault). This can be best avoided by instead having the SDL util functions construct the surfaces on the spot instead creating an returning a descriptor. See the way I did it in the bindings I was working on before for an example of that: https://github.com/JopStro/webgpu-odin/blob/master/webgpu/sdl/sdl.odin~~ addressed in PR #4

## Overbearring abstraction of swap chains
The whole thing with surface_configure to me seems completely baffiling to me. It doesn't save any significant lines of code in practice and only serves to distance the wrapper from and obfuscate the underlying API, it's usage also imposes a bunch of restrictions that could bite back at the user later, such as tying the surface to an individual device and not allowing for multiple swap chains. This functionallity should just be removed as there is no meaningful downside to just using swap chain as is instead.

Those are the core things I've noticed, I may have forgotten some or missed a couple when exploring the API, I'll make sure to add any additional issues if I stumble upon anything else of the sort.

Like I said I'm going to work on refactoring the custom allocator stuff first as I'm quite familiar with that. Feel free to work on the other two if you would like, I'll get round to them myself otherwise.

**Comment by Capati** [comment]
Thanks again for the feedback, your work is really helpful, specially because it’s helping me to understate other stuff e making the bindings useful for others.

The dangling pointers from sdl utils are coming from `Surface_Descriptor` fields that expect a pointer? We could create the surface as you said, or remove the need for a pointer:

````odin
Surface_Descriptor :: struct {
    label:                 cstring,
    Android_Native_Window: Surface_Descriptor_From_Android_Native_Window,
    Html_Selector:         Surface_Descriptor_From_Canvas_Html_Selector,
    Metal_Layer:           Surface_Descriptor_From_Metal_Layer,
    Wayland_Surface:       Surface_Descriptor_From_Wayland_Surface,
    Windows_HWND:          Surface_Descriptor_From_Windows_HWND,
    Xcb_Window:            Surface_Descriptor_From_Xcb_Window,
    Xlib_Window:           Surface_Descriptor_From_Xlib_Window,
}
````

The abstraction of swap chains was to be similar to the WebGPU spec, like the Rust Api, I'm sure there is more than just abstraction like I did.

**Comment by JopStro** [comment]
I did consider the possibility of not requiring pointers, we could use a union as only one of them should be required per descriptor. It should make it more idiomatic too.

In regards to swap chains, delving into the rust API code it does kind of look like what it's doing (I know next to 0 rust). I don't really see much reason for us to do it like that ourselves though as it doesn't seem to be shared by any other APIs I've looked at (for example webgpu.hpp (c++), wgpu-py and go-wgpu). It's just as easy to use the Swap_Chain type as it is anyway, and I personally think it's better for understanding what's going on underneath.

Also glad to hear I've been helpful.

**Comment by Capati** [comment]
I think wgpu-py does something similar, but with a "gpu context". But let's refactor, there is not much reason indeed.

**Comment by Capati** [comment]
You will be working in the last one? I can update the examples later...

**Comment by JopStro** [comment]
It's quite late so I'll probably do it tommorrow, but I probably will.

**Comment by Capati** [comment]
The commit 220fd8a solved the last one, I updated the examples too...

**Comment by JopStro** [comment]
Great stuff
